### ISSUE TITLE
E-antic 0.1.7 does not accept Flint 2.6.1

### ISSUE THREAD

**Issue by w-bruns** [videlec/e-antic#111]
Since Normaliz installs Flint 2.6.0 this is no problem in general.

But: in order not to exceed the maximum of 50 minutes on Travis, our Mac builds draw Flint from HomeBrew, and it delivers Flint 2.6.1, at least by default. Since e-antic/e-antic.h insists on Flint 2.5.2, 2.5.3 or 2.6.0, we have a problem.

**Comment by slel** [comment]
Is this fixed by #112? Will there be a new release?
See Sage ticket about upgrade to Flint 2.6.1
https://trac.sagemath.org/ticket/29719

**Comment by dimpase** [comment]
#112 appears to fix the incompatibility with 2.6.1, but it has to become either a patch for https://trac.sagemath.org/ticket/29719 or
a new release

**Comment by videlec** [comment]
fixed in #112 which is merged in master0
