### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by saraedum** [videlec/e-antic#115]
Working on #114 it's a bit annoying that we do not have any benchmarks. Should we introduce [asv](https://asv.readthedocs.io/en/stable/) benchmarks like we have them on the flatsurf projects?

**Comment by videlec** [comment]
Sure. Why not?

**Comment by saraedum** [comment]
Since I'd like to use the same benchmark framework, the benchmarks would be compiled as C++ code (even though they test C code.)

**Comment by videlec** [comment]
Would that be a source of any problem?

**Comment by saraedum** [comment]
No, I don't think so. Some people dislike C++ so I thought I mention it before creating any benchmarks :)

**Comment by videlec** [comment]
I am one of them :-)
