### ISSUE TITLE
Simplify c++ operators

### ISSUE THREAD

**Issue by saraedum** [videlec/e-antic#14]
Should we use https://www.boost.org/doc/libs/1_69_0/libs/utility/operators.htm to simplify the operator creation that you currently do with macros?

**Comment by videlec** [comment]
I am not familiar with boost. If you propose a pull request I will merge it. The current code is painful to maintain.

**Comment by videlec** [comment]
Though this would add dependency on boost.

**Comment by saraedum** [comment]
It's a header-only dependency for E-ANTIC's C++ header. It does not add a dependency at link time. However, it's most likely going to be a backwards incompatible ABI change; but so are e.g. the changes in #20.
