### ISSUE TITLE
C++ namespace

### ISSUE THREAD

**Issue by saraedum** [videlec/e-antic#15]
Currently, the classes defined by the C++ header live in the global namespace. Though conflicts are unlikely, I think it would be standard practice to move everything into a `namespace eantic` or something like that.

**Comment by videlec** [comment]
Sure. Please add a pull request.

**Comment by videlec** [comment]
Though this would be a backward incompatible change...

**Comment by saraedum** [comment]
Yes, it's a backwards incompatible API & ABI change. However, it's easily fixed by a few using statements. How many projects depend on E-ANTIC?

**Comment by videlec** [comment]
That I know of, two: [https://www.normaliz.uni-osnabrueck.de/] and flatsurf.

**Comment by videlec** [comment]
done in e8eac4d
