### ISSUE TITLE
Reduce use of raw pointers in C++

### ISSUE THREAD

**Issue by saraedum** [videlec/e-antic#19]
Isn't the `operator>>` leaking memory at the moment? Or rather, it's surprising that you have to explicitly free the number field of the element created with it. I guess it would be beneficial to drop all raw pointers and use `shared_ptr` instead? There is a small performance impact but it should not be noticeable.

**Comment by videlec** [comment]
Which line is freeing anything? `reset_parent` is about freeing either the `fmpq_t a` or `renf_elem_t b` that are the elements. The point being that if a `renf_elem_class` is created from a rational number then no `renf_t` parent is ever created for it (the `renf_class *nf` pointer will be `nullptr`). It might have been cleaner with a `union` instead of two attributes `a` and `b`...

**Comment by saraedum** [comment]
Sorry, I should have been more specific.

https://github.com/videlec/e-antic/blob/master/e-antic/renfxx.h#L258 creates `nf`. It is very surprising that the caller needs to explicitly `delete &element.parent()` before `element` goes out of scope.

**Comment by videlec** [comment]
An element should never create any field. This line is supposed to make the `nf` attribute points toward whatever is in the internal extensible array of the stream.

**Comment by saraedum** [comment]
Ok. So rather when the streams internal buffer goes away, `this->nf` points to some random memory?

**Comment by saraedum** [comment]
I'm confused how this works actually. `pword`'s documentation says
>  The reference returned is guaranteed to be valid at least until another operation is performed on the stream object, including another call to pword. Once another operation is performed, the reference may become invalid, although a subsequent call to this same function with the same idx argument returns a reference to the same value within the internal extensible array.

**Comment by videlec** [comment]
Whatever is in the string internal array is a reference to a field the user created. In particular, not owned by the stream. It is just use to set elements from strings as in https://github.com/videlec/e-antic/blob/master/renfxx/test/t-stream.cpp#L73-L91 (that does not leak).

**Comment by saraedum** [comment]
I probably fail to understand what's the use case of this `operator>>`. I assumed it was some sort of deserialization?

**Comment by saraedum** [comment]
Ok. I see now how this is supposed to work. Sorry for the noise. It doesn't leak. I am not sure whether this is the standard way to use `istream` since I've never used that for such a purpose.

**Comment by videlec** [comment]
This is used to read a field and many elements from a file.

**Comment by videlec** [comment]
Could we close the issue?

**Comment by saraedum** [comment]
Yes, I would not want to reduce any more pointers.
