### ISSUE TITLE
Compile renfxx / add forwarding header

### ISSUE THREAD

**Issue by saraedum** [videlec/e-antic#25]
What is the reason that the entire implementation of `renfxx` lives in the header? Since it does not use any templates, I guess it could be moved to compiled files? This would speed up compilation when including `renfxx.h`.

Of course this makes inlining a bit harder but to my knowledge, you get the same speed when using `-flto -fno-semantic-interposition`, at least that's what I am using at flatsurf.

Also, it would be nice to have a forwarding header, `renfxx_fwd.h` that just forward declares everything without any implementation. In header files this is usually all you need and obviously this helps with compilation (e.g., I won't have to pull in the entire `gmpxx.h` transitively just because I declare a method taking a `renf_elem_class`.)

I volunteer to do both of these if you think it's a good idea.

**Comment by videlec** [comment]
Anything that makes compilation easier and make the code more C++ complient is good to take. Please do.
