### ISSUE TITLE
remove support for rationals in renf_elem_class

### ISSUE THREAD

**Issue by videlec** [videlec/e-antic#28]
The `renf_elem_class` is a fake union type of `renf_elem_class` and `fmpq_t`. Because of this, a lot of code in the C++ interface is just dedicated to the proper dispatch. Since the GMP C++ classes `mpz_class` and `mpq_class` are fully compatible with `renf_elem_class` we should just get rid of this fake union type and have `renf_elem_class` to carry only the two attributes
```
renf * nf; // parent number field
renf_elem_t a; // the actual element
```

**Comment by saraedum** [comment]
So this is going to go into 1.1 most likely. We want to keep the `nf == nullptr` logic for the time being. Should this depend on #30 ?

**Comment by saraedum** [comment]
Maybe this should also go into 1.0 since it breaks ABI (the size of renf_elem_class changes.)
