### ISSUE TITLE
Work around missing C11 support

### ISSUE THREAD

**Issue by saraedum** [videlec/e-antic#34]
The C11 standard defining the mutexes that I used in the renf refinement has only been implemented by glibc in mid 2018. So it's not widely available. (I am ignorant of the C world I have to admit and had assumed that something that said 20**11** would be completely standard by now.)

**Comment by saraedum** [comment]
Since we're only doing POSIX platforms at the moment anyway, I guess I'll change this to use `pthread`?

**Comment by videlec** [comment]
After thinking about this, it would be much better if pthread would not be mandatory. In the older version, open mp was just an optional dependency.
