### ISSUE TITLE
move back to C++11 or at least C++14

### ISSUE THREAD

**Issue by videlec** [videlec/e-antic#37]
As mentioned by Winfried Bruns, C++17 is not working for Normaliz developers.

**Comment by fingolfin** [comment]
This would indeed be nice. Not so much because it doesn't work for the Normaliz developers, but rather because it is a considerable hurdle when deploying the software to users who don't have recent compiler versions. Of course in an ideal world, there'd be easy to use binary distributions of software for everybody, but (a) that's not the case in practice, and (b) many "users" in fact are developers themselves, and they may have reasons why they can not or do not want to use the latest compiler versions (e.g. because their code is run on a HPC cluster where only a fixed set of compilers is available).

Believe me, I'd prefer to use C++14 and C++17 and C++20 and whatever myself, but I've been bitten by the issues described above, and many times more often by users, and that was just for relying on, say, GCC 5 (in GAP, we have people who for various reasons are stuck to GCC 4.4.6 ... *sigh*).

**Comment by saraedum** [comment]
Thanks for the explanation.
My understanding is that e-antic is not an integral part of normaliz. I guess it's reasonable for normaliz to be at least C++17 compatible though I understand that some of your dependencies have not been yet, last time we discussed this.
Anyway, if normaliz were C++17 compatible, then it should be easy to keep it C++11 compatible when it's built `--without-eantic`.

**Comment by fingolfin** [comment]
What is not C++17 compatible in Normaliz?

**Comment by saraedum** [comment]
cocoalib (if I spell that correctly) was using auto_ptr which were removed in C++17.

**Comment by fingolfin** [comment]
@saraedum ah, I see. Well, they decided against migrating away from auto_ptr, it seems, see <https://cocoa.dima.unige.it/redmine/issues/891>, with the comment "NOT C++03 COMPATIBLE (not worth it)".

I guess someone would have to talk to them and convince them otherwise.

**Comment by fingolfin** [comment]
Perhaps @w-bruns has good contacts? I don't know any of the CoCoA developers.

**Comment by fingolfin** [comment]
Ah, bad perhaps I am also misreading that close CoCoA issue? Because there is an "Design" issue discussing a move to C++14, skipping C++11: https://cocoa.dima.unige.it/redmine/issues/1225

**Comment by w-bruns** [comment]
I have mentioned the auto_ptr problem several times with the authors of CoCoALib. They told me that they want to migrate to a newer C++ standard. I am in Genova now and will right away go to see Anna Bigatti -- if she is in the institute.

**Comment by w-bruns** [comment]
John Abbott has announced to update CoCoALib to C++14.

My suggestion: set e-antic back to C++14. In this way not too many users are excluded. In 2 or 3 years one can take up this issue again.

**Comment by saraedum** [comment]
Correct me if I am wrong but C++14 features are a superset of C++11 so I am not sure what he means when he wants to update to C++14.

So they will not drop the auto_ptr?

Btw here's my little inofficial list what compilers are shipped in certain distros:

Ubuntu 18.04 LTE: gcc7
Debian stable (and related such as Mint I  guess): gcc8
Archlinux (and afaik Manjaro): gcc9
OpenSUSE: gcc9 (to my surprise)
Fedora: gcc8
CentOS/RHEL-7: gcc4
Gentoo: gcc9
ScientificLinux (afaik essentially a CentOS): gcc4
Nix/Guix: Not sure what's the default but I am strongly suspecting that they ship a recent gcc.
Brew: gcc9
Conda: gcc7 (clang4 on macOS but that's about to change.)
Cygwin: gcc7

That's all the distros I've ran across outside the container world in recent years I think. gcc 7 supports C++17 in its entirety.

**Comment by fingolfin** [comment]
I think what it means is that they will immediately require C++14 themselves, and they already dropped `auto_ptr` internally (just not yet in a released version).

And yeah, current distros have current compilers. But I am dealing with people who use university clusters where the latest available compiler is GCC 4.4.6, I am afraid... But of course one can decide to ignore them, as long as it's a conscious decision *shrug*.

**Comment by saraedum** [comment]
Ok. Ignoring them as in telling them not to use `--with-eantic` sounds fair to me.

**Comment by fingolfin** [comment]
Well, as you list yourself: CentOS 7 is on GCC 4.8.6, and many HPC clusters seem to use that. So you exclude those users if you require C++14 or C++17. But of course with gcc 4.8, one is basically restricted to C++11. Which isn't great. (CentOS 8 has gcc8 -- but CentOS 8 was released yesterday, so... :-).

BTW, I found most of this info using https://repology.org/project/gcc/versions (and then https://pkgs.org/download/gcc to check for CentOS 8, but pkgs.org hasn't the best search interface, sadly).

**Comment by saraedum** [comment]
So backporting to C++14 would not really help much actually. We would have to go to C++11. And  you would not be able to upgrade cocoalib if I understand correctly.

**Comment by fingolfin** [comment]
Indeed

**Comment by w-bruns** [comment]
I will try try to find out what X++14 means for CoCoALib, but I am sure that the auto_ptr will disappear.

**Comment by saraedum** [comment]
@w-bruns any update on this?

**Comment by w-bruns** [comment]
Yes. The three releases of CoCoALib are on C++14 level. No offending syntax anymore.

The configure script now insists that the compiler guarantees C++14. The new versions can't be build with Ubuntu Trusty, even if the source code would permit this. I haven't tried Xenial. Bionic works for sure.
