### ISSUE TITLE
Python interface

### ISSUE THREAD

**Issue by saraedum** [videlec/e-antic#47]
I'd like to interact with https://github.com/flatsurf/flatsurf/ through a Python interface (so we can eventually use it from Jupyter notebooks.) While I probalby wouldn't want to do anything non-trivial in Python with `renf_elem_class` and `renf_class`, it would be nice to be able to create inputs from there. E.g., I would like to be able to write down elements of modules in https://github.com/flatsurf/exact-real to describe polygons.

I think it would be quite easy to make `renf_class` and `renf_elem_class` available to Python through cppyy and make arithmetic of elements work. Actually, modulo https://bitbucket.org/wlav/cppyy/issues/94/sigsegv-in-tclass-getbaseclass-with-boost it already works though the interface is not too convenient. Making this pretty comes down to one extra header, say `cppyy.h` which defines global versions of `operator<<` and a bit of Python glue similar to https://github.com/flatsurf/exact-real/pull/18 but likely much less since we do not have to work around issues with yap here.

It might be convenient to put this into a new repository since the autotools setup is quite different. (It being a pure Python project with one .h file.)

What do you think?

**Comment by videlec** [comment]
+1! This definitely should be a disjoint repo. Please make it compatible with [gmpy2](https://github.com/aleaxit/gmpy) that stands for Python wrapper for GMP, MPFR and MPC. That is to say
 * Python classes should be called `renf` and `renf_elem` (they are called `mpz`, `mpq`, `mpfr`, `mpc` in gmpy2)
 * a C API
 * a minimal Cython interface (see [src/gmpy2.pxd](https://github.com/aleaxit/gmpy/blob/master/src/gmpy2.pxd))
 * make the conversion `mpz/mpq` -> `renf_elem` work
Do you know about `flint`/`arb` Python wrappers?

**Comment by saraedum** [comment]
I haven't had a look at gmpy2 yet, but I suppose it does not wrap the C++ wrappers of GMP but talks to GMP directly. I guess we'd need yet another library (though it could be the same) that wraps `mpz_class` and friends as the corresponding gmpy2 types. Not sure how hard it would be two make this work conveniently.

I don't really understand some of the other things you wrote:

What do you mean by a C API? What I am planning is a Python library that essentially lets C++ do all the heavy lifting. So there's no C involved and in particular I am not planning on extending the C/C++ interface in any way.

I don't think there should be a Cython interface since this is going to be a pure Python library (that calls into cppyy.)

The conversion `mpz_class` → `renf_elem_class` worked out of the box. Making the conversion from gmpy2's `mpz` work is mostly about making `mpz` and `mpz_class` interchangeable. I am not sure how hard that would be.

As for `arb` wrappers, there is the one that we get for free from `exact-real` (probably should be moved out of exact-real eventually.) https://github.com/flatsurf/exact-real/pull/18/files#diff-e9c80d4e8cd04a3054dbed1826ecabee

I am not aware of any FLINT wrappers. The C++ interface they have does imho not help when trying to move this to Python as it only exists at compile time. cppyy can talk to FLINT's C API but that doesn't feel like Python anymore then.

**Comment by videlec** [comment]
> I haven't had a look at gmpy2 yet, but I suppose it does not wrap the C++ wrappers of GMP but talks to GMP directly.

This is correct.

> What do you mean by a C API?

Creation of `PyObject *` from C/C++. This would be need for e.g. PyNormaliz to make proper conversions.

> I am not aware of any FLINT wrappers.

What about https://pypi.org/project/PyFlint/?

**Comment by saraedum** [comment]
pyflint: Open sourced components of Alpine's Spark Autotuning functionality ;)

**Comment by saraedum** [comment]
This is now flatsurf/pyeantic.

**Comment by saraedum** [comment]
I pushed a version there that seems to do something useful. Please have a look :)

**Comment by videlec** [comment]
Should we merge pyeantic inside eantic (as it is with exactreal and flatsurf)?

**Comment by saraedum** [comment]
I quote ;)
> This definitely should be a disjoint repo.

**Comment by saraedum** [comment]
I would not mind merging but I think I prefer my build stack over your direct invocation of travis. But I am not completely sold on that one either.

**Comment by videlec** [comment]
Ok. Let us keep it the way it is :-)
