### ISSUE TITLE
c++ tests do not build on Travis-CI

### ISSUE THREAD

**Issue by videlec** [videlec/e-antic#7]
The log of the build is https://travis-ci.org/videlec/e-antic/jobs/351823311#L9276

Apparently the linker does not know that it has to link with `flint`/`arb`/`nfemb`...
```
g++ -DPACKAGE_NAME=\"e-antic\" -DPACKAGE_TARNAME=\"e-antic\" -DPACKAGE_VERSION=\"0.1\" -DPACKAGE_STRING=\"e-antic\ 0.1\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"e-antic\" -DVERSION=\"0.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I.  -I../..   -g -O2 -MT t-renfxx.o -MD -MP -MF .deps/t-renfxx.Tpo -c -o t-renfxx.o t-renfxx.cpp
mv -f .deps/t-renfxx.Tpo .deps/t-renfxx.Po
/bin/bash ../../libtool  --tag=CXX   --mode=link g++  -g -O2   -o t-renfxx t-renfxx.o ../../libnfemb.la -lgmpxx -lgmp
libtool: link: g++ -g -O2 -o .libs/t-renfxx t-renfxx.o  ../../.libs/libnfemb.so -lgmpxx -lgmp
/usr/bin/ld: t-renfxx.o: undefined reference to symbol '_fmpz_clear_mpz'
//usr/lib/libflint.so.13: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
To be compared to what I have on my computer
```
g++ -DHAVE_CONFIG_H -I. -I../..  -I../..   -g -O2 -MT t-renfxx.o -MD -MP -MF .deps/t-renfxx.Tpo -c -o t-renfxx.o t-renfxx.cpp
mv -f .deps/t-renfxx.Tpo .deps/t-renfxx.Po
/bin/sh ../../libtool  --tag=CXX   --mode=link g++  -g -O2   -o t-renfxx t-renfxx.o ../../libeantic.la -lgmpxx -lgmp
libtool: link: g++ -g -O2 -o .libs/t-renfxx t-renfxx.o  ../../.libs/libeantic.so -lantic -larb -lflint -lgmpxx -lgmp -Wl,-rpath -Wl,/usr/local/lib
```

**Comment by videlec** [comment]
For now it is fix by installing the headers and libraries in /usr/local and adding /usr/local/lib to the LD_LIBRARY_PATH

**Comment by saraedum** [comment]
Is this what is keeping you from enabling Travis for Pull Requests?

**Comment by saraedum** [comment]
Just realized that they are enabled. But it seems you don't allow travis to report back to github?

**Comment by saraedum** [comment]
Is this still an issue? Your `configure.ac` at that point did not search for flint it seems.

**Comment by videlec** [comment]
This is still an issue. Linking works fine because of [https://github.com/videlec/e-antic/blob/master/.travis.yml#L17](line 17 in .travis.yml).

**Comment by saraedum** [comment]
I don't understand. `make check` seems to work on TravisCI currently. Or are the C++ tests disabled somehow?

**Comment by videlec** [comment]
It should not be needed to export the `LD_LIBRARY_DIR` variable (am I wrong?).

**Comment by saraedum** [comment]
`LD_LIBRARY_PATH` usually means something is wrong I agree. But you have to tell configure about your non-standard library path. Have you tried setting `LDFLAGS=-L/usr/local/lib`?

**Comment by saraedum** [comment]
Sorry, you're actually doing that.

**Comment by saraedum** [comment]
So, the report on top is outdated, right? It's not the building that fails but actually running the tests. That's expected without setting `LD_LIBRARY_PATH`. The dynamic linker does not find the libraries.

**Comment by videlec** [comment]
indeed
