### ISSUE TITLE
c++ tests do not work with VPATH build

### ISSUE THREAD

**Issue by videlec** [videlec/e-antic#8]
The culprit is probably `e-antic/test/Makefile.am` that is not careful enough with includes.
```
$ mkdir whatever
$ cd whatever
$ ../configure
$ make check
...
  CXX      t-renfxx.o
../../../e-antic/test/t-renfxx.cpp:12:10: fatal error: e-antic/renfxx.h: No such file or directory
 #include "e-antic/renfxx.h"
```

See also [the discussion on automake mailing list](http://lists.gnu.org/archive/html/automake/2018-03/msg00017.html).

**Comment by saraedum** [comment]
works for me.

**Comment by videlec** [comment]
for me too... I am not sure what changed.
