### ISSUE TITLE
Support operations between elements from different fields

### ISSUE THREAD

**Issue by giomasce** [videlec/e-antic#88]
Currently if one tries to do an operation (say, an addition) between elements coming from two different classes [an exception is thrown](https://github.com/videlec/e-antic/blob/master/renfxx/renf_elem_class.cpp#L628), because the library doesn't know how to embed both elements in a common field. Is implementing this feature planned? Can I help with it? I am able to contribute C++ and I am a mathematician (although not specializing in algebra or number theory). If you have papers or references that describe the algorithm, I can try to implement them.

**Comment by videlec** [comment]
This error is not thrown when two different classes are used but rather when two `renf_elem_class` have different underlying number field (what is called the `parent` in the C++ interface). The reasons why this is not be implemented are multiple. Most importantly, there is no canonical parent to adopt the result of the operation (eg a number field has infinitely many generators).

In which context do you need such feature? It sounds to me that you would better used more advanced algebra softwares such as [SageMath](https://www.sagemath.org).

As far as eantic is concerned a useful addition would be to have (injective) morphisms between number fields. That way you could at least do
```
x1 = myElementFromFieldK1
x2 = myElementFromFieldK2
L = myFieldContainingBothK1AndK2
phi1 = K1.embedding(L)
phi2 = K2.embedding(L)
phi1(x1) + phi2(x2)   // would make the result of x1 + x2 lives in L
```

**Comment by giomasce** [comment]
Something like rings AA and QQbar in SageMath is really the thing I'd like to have, but for C++. I have an application where I need an exact field where I can also extract roots. Currently I use some hacks to determine a priori which field I'll be working with, but this is quite inconvenient. I would like if, like SageMath, the library would let single elements track their field for me.

If this can be considered in-scope for e-antic, I can try to help to code it. Otherwise, thanks for the rest! :-)

**Comment by videlec** [comment]
Indeed SageMath AA and QQbar does involve some book-keeping about "compositum" of fields. It also uses some subtle PARI/GP features (such as `polredbest`). This is a lot of work to implement properly.

I know that B. Hart (author of antic) and F. Johansson (author of arb) were interested by such project. You might want to contact them.

**Comment by giomasce** [comment]
Thanks.
